---
title: "Dissecting the quick fix"
subtitle: "Analysing tech-solutionist solutions"
format: revealjs
editor: visual
---

## Tech solutionism

</br /></br /></br /></br />

> The tendency to use technology to solve a societal (political, organizational, environmental ...) problem.

::: notes
Often defined as "the belief that technology can be used to solve any problem". Doesn't have to be put in so strong a way, though.

Let me give just three quick, non-fictitious examples to make clear what this is about.
:::

## Example: Suppressed population groups rising up

. . .

-   [*Problem*]{style="color: #645394;"}: Suppressed population groups (e.g., ethnic minorities) start to mobilise.

. . .

-   [*Observation*]{style="color: #645394;"}: This is more likely to happen / to become violent when it is hot -- very hot.

. . .

-   [*Solution*]{style="color: #645394;"}: Install climatization throughout.

. . .

-   [*Gain*]{style="color: #645394;"}: We don't have to actually address those groups' demands.

## Example: Mass shootings

. . .

-   [*Problem*]{style="color: #645394;"}: Since 2014, the US has averaged more than one mass shooting a day.

. . .

-   [*Observation*]{style="color: #645394;"}: You can't always see if someone is carrying a gun.

. . .

-   [*Solution*]{style="color: #645394;"}: Install advanced surveillance technology.

. . .

-   [*Gain*]{style="color: #645394;"}: We don't have to change the laws related to gun ownership.

## Example: Climate change

. . .

-   [*Problem*]{style="color: #645394;"}: Climate change is rendering parts of the Earth inhabitable, and significantly deteriorates living conditions in others.

. . .

-   [*Observation*]{style="color: #645394;"}: Time is passing, and we are less and less on track for keeping the situation under control.

. . .

-   [*Solution*]{style="color: #645394;"}: Move to Mars (or wherever, in space).

. . .

-   [*Gain*]{style="color: #645394;"}: \*We\* survive (and get to have "fun").

::: notes
Now, with the last example, you're probably noticing we're getting close to a sarcastic, cynical way of talking about the topic. Indeed, it would be easy to go on bringing revolting, disgusting examples. But disgust really does not lead us anywhere. For example, moving to space evidently is absurd and injust; but what about other "tech fixes" proposed to handle climate change -- the various forms of so-called "geoengineering"? If we rely on (shared) disgust and outrage only ... - we won't be able to spot less aversive cases - we won't be able to convince others
:::

## Let's instead see what's so seductive about it

::: notes
-   It *solves* a problem. (A tautology, but an important one.)
-   It solves a *problem*. (It matters.)
-   It solves a *hard* problem. (Why else would we care.)
-   It solves a *problem* we don't really know how to solve otherwise. (And there are many of them.)
-   It solves a *problem* whose other solutions would involve *sacrifices*. (That's the last thing we want.)
-   It solves a problem we're terribly *scared* about.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
It solves a problem we're terribly scared about.
:::

## We need to be more clear about how we assess "solutions"

::: notes
So, if we do see that solutionism can look attractive ... what can we do

We would like

-   A framework to analyze a "solution" along explicitly stated, communicable, and weightable dimensions.
-   BUT: An analysis may NOT be restricted to the purely technical.
-   Suggestion: For maximum openness and generality, follow the **W**-questions (what, where, when, who, why - plus how).
-   To counter-balance the usual type of discourse, we'll want to re-distribute focus from the WHAT to the *WHO* and *WHY*.
:::

. . .

<br /> <br />

Commonly, the focus is on the *what* and maybe, the *where* and the *when*. (Sometimes, even the *how*).

<br />

I would like to focus on the neglected [*why*]{style="color: #645394;"} and [*who*]{style="color: #645394;"}.

# Not "just" [*what*]{style="color: #645394;"} (and [*where*]{style="color: #645394;"} and [*when*]{style="color: #645394;"} and [*how*]{style="color: #645394;"}): But [*why*]{style="color: #645394;"} and [*who*]{style="color: #645394;"}

::: notes
Since those won't be in-focus: What do I mean by WHAT, WHERE, WHEN, and HOW?

-   *What* does the "solution" do? I.e. the complete technical workflow, starting from what datasets were used, how a model was trained, up to and including how it was evaluated.
-   *Where*, *when*, and *to whom* will the "solution" be applied? I.e. the complete (geographical, social, political) context.
-   *How* exactly will the solution be applied? Details matter.
:::

# Dissecting the [*why*]{style="color: #645394;"}

## [*Why*]{style="color: #645394;"}: What'll you hear

::: notes
-   We want to help.
-   We care.
-   We're here for you.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
We're here for you.
:::

## [*Why*]{style="color: #645394;"}: What you *won't* hear - individual reasons

::: notes
-   This will look good on my resume.
-   This just might get me a job at \[company x\].
-   This is something one could launch a startup for.
-   This is a great reason to learn/use technology \[insert currently-hyped technology here\].
-   It's just so cool that this *can even be done*.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
It's just *so* cool that this can even be done.
:::

## [*Why*]{style="color: #645394;"}: What you *won't* hear - organizational reasons

::: notes
-   If we do this, we'll be strengthening our existing \[but always threatened\] monopoly.
-   If we do this, we distract from \[that unfortunate thing that went through the news\].
-   If we do this, everybody will see we're the good guys.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
We're the good guys.
:::

## [*Why*]{style="color: #645394;"}: What you won't hear - side effects

::: notes
-   If we implement this, we'll be able to harvest valuable data \[to be used in targeted advertising\].
-   If we implement this, we'll be able to harvest valuable data \[to be used to train our neural networks\].
-   If we do this, we'll have a foot in the door to \[build that yet more impactful thing\].
-   If we do this, public institutions will be seriously reliant on us.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
Public institutions will be seriously reliant on us.
:::

## [*Why*]{style="color: #645394;"}: What you *won't* hear - power

::: notes
-   If we do this, we can seriously shape how people live.
-   If we do this, we can seriously shape how people think.
-   If we do this, we can seriously shape how people feel.
-   If we do this, we can seriously shape who people *are*.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
If we do this, we can seriously shape who people *are*.
:::

# Dissecting the [*who*]{style="color: #645394;"}

## [Who]{style="color: #645394;"} is *who*?

<br />

::: notes
Who is ambiguous and could mean many things. I'm using it in a specific sense.
:::

-   Who designs, implements, and hosts the "solution"?
-   Who processes its data?
-   Who knows how it works, and can fix problems?

<br />

::: notes
Let's investigate this by example: Education technology (a.k.a. edtech)
:::

## Edtech: What'll you hear

::: notes
-   With \[adaptive technology x\], each learner's individual needs are met.
-   Thanks to \[x\], teachers have time to focus on what they do best.
-   With technology \[x\], we make learning more effective and efficient.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
We make learning more effective and efficient.
:::

## Edtech: What you *won't* hear -- how it works

::: notes
-   We record, process and store a lot of \[extremely\] personal data.
-   We constantly track and analyze your behavior.
-   You learn; *we're learning* from you.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
You learn; *we're learning from you.*
:::

## Edtech: What you *won't* hear -- market domination

::: notes
-   Once we have "gotten in", network effects will make it things very hard for hypothetical competitors.
-   Once we have "gotten in", anyone who wants in has to follow our rules.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
Want in? Follow our rules.
:::

## Edtech: What you *won't* hear -- shaping society

::: notes
-   We define *how* people learn.
-   We define *what* is learned.
-   We define what *deserves* to be learnt.
-   We define what *deserves* to be forgotten.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
We define what deserves to be forgotten.
:::

## Edtech: What you *won't* hear -- the concept of humanity

::: notes
-   We define the past.
-   We define the present.
-   We define the future.
-   We define what it means to be human.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
We define what it means to be human.
:::

# Can you say again how this is about the [*who*]{style="color: #645394;"}?

::: notes
We said that the WHO was about who designs, implements, and hosts the solution; who has access to its data; who can fix it.
:::

## Imagine a dimension, *public ... private*

+-------------+------------------------------------------------------------+--------------------------------------------------+
|             | PUBLIC                                                     | PRIVATE                                          |
+=============+============================================================+==================================================+
| | Examples  | (true) democracy                                           | corporation, foundation, NGO                     |
+-------------+------------------------------------------------------------+--------------------------------------------------+
| | Features  | democratic decision process, participation, supra-locality | lack of the ones to the left; otherwise, varying |
+-------------+------------------------------------------------------------+--------------------------------------------------+
| | Values    | fairness, justice, human rights, accountability            | dependent on political agenda                    |
+-------------+------------------------------------------------------------+--------------------------------------------------+

::: notes
Then what difference would it make who's the who?
:::

## Difference no. 1: Business models

::: notes
-   Public institutions do not need to extract private data to make money.

-   Public institutions do not need to feed back fresh data into their large deep learning models.

-   Public institutions do not need to worry about competition.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
Public institutions do not need to worry about competition.
:::

## Difference no. 2: Political and legal aspects

::: notes
-   Public institutions can be held to ensure transparency.
-   Public institutions can be held to ensure that errors are fixed.
-   Public institutions can be held *accountable*.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
Public institutions can be held *accountable*.
:::

## Difference no. 3: Human rights and values

::: notes
-   Public institutions can be held to respect human rights.

-   Public institutions can be held to prioritize values over feasibility.

-   Public institutions can be held to promote -- not eliminate -- people's individuality.
:::

. . .

<br /> <br /> <br />

::: {style="text-align: center;"}
Public institutions can be held to promote individuality.
:::

# Yes, but still. How does this concern *me*?

::: notes
I'm neither a state nor a CEO. How can I influence any of that?

-   But we all make choices (where we work, how we vote, whether we engage politically...)
-   If nothing else, we can try to keep questioning the things we're told.
-   And maybe we could just start with some imagination ... about data science in a more just world.
:::

## Maybe data science could be different

<br />

What if ...

<br />

-   Data were used not to perpetuate, but [*change*]{style="color: #645394;"} the status quo?
-   Data were used to make social relations more [*egalitarian*]{style="color: #645394;"}, more [*just*]{style="color: #645394;"}?
-   Data were used to [*subvert*]{style="color: #645394;"} privileges, not [*reinforce*]{style="color: #645394;"} them?
